server {
    listen 80 default_server;
    server_name _;

    location = /healthz {
        access_log off;
        add_header Content-Type text/plain;
        return 200 'ok';
    }

    location /html5client/locales {
        alias /usr/share/bigbluebutton/html5-client/locales;
        autoindex on;
        autoindex_format json;
    }

    location /html5client/wasm {
        types { application/wasm wasm; }
        gzip_static on;
        alias /usr/share/bigbluebutton/html5-client/wasm;
    }

    location /html5client {
        gzip_static on;
        alias /usr/share/bigbluebutton/html5-client/;
        index index.html;
        try_files $uri $uri/ /html5client/index.html;
    }

    location /learning-analytics-dashboard {
        alias /www/learning-analytics-dashboard/;
        index index.html;
        try_files $uri $uri/ /learning-analytics-dashboard/index.html;
    }

    location /graphql {
        proxy_pass http://graphql-middleware:8378;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 3600s;
    }

    location / {
        return 302 /html5client/;
    }
}
