#!/bin/bash
set -euo pipefail

export PGHOST="${PGHOST:-postgres}"
export PGUSER="${POSTGRES_USER:-postgres}"
export PGPASSWORD="${POSTGRES_PASSWORD:-password}"
export PGPORT="${PGPORT:-5432}"

export HASURA_GRAPHQL_DATABASE_URL="${HASURA_GRAPHQL_DATABASE_URL:-postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/hasura_app}"
export HASURA_GRAPHQL_METADATA_DATABASE_URL="${HASURA_GRAPHQL_METADATA_DATABASE_URL:-$HASURA_GRAPHQL_DATABASE_URL}"
export HASURA_GRAPHQL_BBB_DATABASE_URL="${HASURA_GRAPHQL_BBB_DATABASE_URL:-postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/bbb_graphql}"
export HASURA_GRAPHQL_LOG_LEVEL="${HASURA_GRAPHQL_LOG_LEVEL:-warn}"
export HASURA_GRAPHQL_ENABLE_CONSOLE="${HASURA_GRAPHQL_ENABLE_CONSOLE:-true}"
export HASURA_GRAPHQL_SERVER_PORT="${HASURA_GRAPHQL_SERVER_PORT:-8085}"
export HASURA_GRAPHQL_ENABLE_TELEMETRY=false
export HASURA_GRAPHQL_WEBSOCKET_KEEPALIVE=10
export HASURA_GRAPHQL_ADMIN_SECRET="${HASURA_GRAPHQL_ADMIN_SECRET:-bigbluebutton}"
export HASURA_GRAPHQL_AUTH_HOOK="${HASURA_GRAPHQL_AUTH_HOOK:-http://apps-akka:8901/userInfo}"
export HASURA_BBB_GRAPHQL_ACTIONS_ADAPTER_URL="${HASURA_BBB_GRAPHQL_ACTIONS_ADAPTER_URL:-http://graphql-actions:8093}"

exec "$@"
